<?php

namespace EBikeBundle\Repository;

/**
 * MediaHomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaHomeRepository extends \Doctrine\ORM\EntityRepository
{
}
