<?php

namespace EBikeBundle\Repository;

/**
 * PromImgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromImgRepository extends \Doctrine\ORM\EntityRepository
{
}
